builds:
  - goos:
      - linux
    goarch:
      - amd64
      - arm64
    binary: xray-rs
    id: xray-rs
    main: goreleaser.go
    hooks:
      post:
        - ./.goreleaser_hook.sh "{{ .Arch }}" "{{ .Os }}" "xray-rs"

  - goos:
      - linux
    goarch:
      - amd64
      - arm64
    binary: rsdns
    id: rsdns
    main: goreleaser.go
    hooks:
      post:
        - ./.goreleaser_hook.sh "{{ .Arch }}" "{{ .Os }}" "rsdns"

checksum:
  name_template: "checksums.txt"
changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^tests:"
release:
  replace_existing_artifacts: true
  prerelease: auto
