[build.env]
passthrough = ["JEMALLOC_SYS_WITH_LG_PAGE"]

[target.aarch64-unknown-linux-musl]
image = "ghcr.io/cross-rs/aarch64-unknown-linux-musl:main"

[target.x86_64-unknown-linux-musl]
image = "ghcr.io/cross-rs/x86_64-unknown-linux-musl:main"

[target.aarch64-linux-android]
image = "ghcr.io/cross-rs/aarch64-linux-android:main"
